CREATE TABLE `stockdailyinfo` (
  `stockcode` varchar(6) NOT NULL DEFAULT '',
  `stockname` varchar(20) NULL DEFAULT '',
  `tradedate` int(8) NOT NULL DEFAULT '0',
  `openPrice` float DEFAULT NULL,
  `closePrice` float DEFAULT NULL,
  `highestPrice` float DEFAULT NULL,
  `lowestPrice` float DEFAULT NULL,
  `tradeAmount` int(11) DEFAULT NULL,
  `amtAvg5` int(11) DEFAULT NULL,
  `amtAvg10` int(11) DEFAULT NULL,
  `priceAvg5` float DEFAULT NULL,
  `priceAvg10` float DEFAULT NULL,
  `priceAvg20` float DEFAULT NULL,
  `priceAvg30` float DEFAULT NULL,
  `priceAvg60` float DEFAULT NULL,
  `ema12` float DEFAULT NULL,
  `ema26` float DEFAULT NULL,
  `diff` float DEFAULT NULL,
  `dea` float DEFAULT NULL,
  `macd` float DEFAULT NULL,
  `k` float DEFAULT NULL,
  `d` float DEFAULT NULL,
  `j` float DEFAULT NULL,
  `rsv` float DEFAULT NULL,
  PRIMARY KEY (`stockcode`,`tradedate`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
